### PR TITLE
[BUGFIX] Check existing Content-Type is in <head>

### LINKED ISSUE #923: CssInliner getHeadElement Error (missing head)
Hello,

I have this error, i did a little reasearch and i know that its because of missing head tag, i cannot asure the existence of head tag aways because users generate the templates.

Im actually using `HtmlNormalizer::fromHtml(...)->render()` before running `CssInliner::fromHtml(..)->inlineCss()->render()`
Why HtmlNormalizer didn't added the head tag?

```
Exception: Return value of Pelago\Emogrifier\CssInliner::getHeadElement() must be an instance of DOMElement, null returned
/emogrifier/pelago/emogrifier/src/CssInliner.php [ 1169 ]
```

Im using 5.0.x-dev, PHP 7.3

### PR DESCRIPTION
**Pull request by JakeQZ**
If a valid `Content-Type` `<meta>` element is present, DOM conversion will
create a `<head>` element for it even without an explicit `<head>` tag in the
HTML.

However, to be valid, it must not be in the `<body>` element.  As well as with
an explicit `<body>` start tag, the `<body>` element also begins whenever a
start tag for an element which cannot be in the `<head>` is encountered.  This
is now checked.

Fixes #923.

### CODE REVIEW

**Comment by JakeQZ** [comment]
Theres a Psalm error I need to fix...

**Comment by JakeQZ** [comment]
Now fixed the Psalm errors.  (I've not been running it locally because I get about 50 more errors that we don't get on the build server - not sure why, maybe different OS or PHP version - am using the same PHAR.)

**Comment by JakeQZ** [comment]
You'll probably need to edit the commit message and title before merging, as it includes your (@oliverklee) initial WIP commit with tests.

**Comment by JakeQZ** [comment]
Last force-push was just fixing a typo in a comment, and adding a `trigger_error` to capture the unlikely event of `preg_replace` failing internally.

**Comment by JakeQZ** [comment]
Now just moved exception handling to higher level for clarity.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 1]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+            = \preg_match('%<(?!' . static::TAGNAME_ALLOWED_BEFORE_BODY_MATCHER . '[\\s/>])\\w|</head>%i', $html);
+        if (\is_int($headEndTagMatchCount) && $headEndTagMatchCount > 0) {
+            // An exception to the implicit end of the `<head>` is any content within a `<template>` element, as well in
+            // comments.  As an optimization, this is only checked for if a potential `<head>` end tag is found.
+            $htmlWithoutCommentsOrTemplates = $this->removeHtmlTemplateElements($this->removeHtmlComments($html));
+            if ($htmlWithoutCommentsOrTemplates === $html) {
+                $hasEndOfHeadElement = true;
+            } else {
+                $hasEndOfHeadElement = $this->hasEndOfHeadElement($htmlWithoutCommentsOrTemplates);
+            }
```
Comment (oliverklee) [inline src/HtmlProcessor/AbstractHtmlProcessor.php:369]: Shorter:

```php
$hasEndOfHeadElement = $htmlWithoutCommentsOrTemplates === $html || $this->hasEndOfHeadElement($htmlWithoutCommentsOrTemplates);
```

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 2]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+        } else {
+            $hasEndOfHeadElement = false;
+        }
+
+        return $hasEndOfHeadElement;
+    }
+
+    /**
+     * Removes comments from the given HTML, including any unclosed, for which the remainder of the string is removed.
```
Comment (oliverklee) [inline src/HtmlProcessor/AbstractHtmlProcessor.php:378]: This sentence sounds a bit off to me … is there a word missing after "unclosed"?

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 3]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+     *
+     * @param string $html
+     *
+     * @return string
+     *
+     * @throws \RuntimeException
+     */
+    private function removeHtmlComments(string $html): string
+    {
+        $result = \preg_replace('/<!--[^-]*+(?:-(?!->)[^-]*+)*+(?:-->|$)/', '', $html);
```
Comment (oliverklee) [inline src/HtmlProcessor/AbstractHtmlProcessor.php:388]: Can we move the regexp to a well-named local variable (or constant)?

**Review by oliverklee — CHANGES_REQUESTED** [review]

File: psalm.baseline.xml [hunk 4]
```diff
@@ -65,12 +65,13 @@
...
   </file>
   <file src="src/HtmlProcessor/AbstractHtmlProcessor.php">
-    <MixedOperand occurrences="6">
+    <MixedOperand occurrences="7">
       <code>static::PHP_UNRECOGNIZED_VOID_TAGNAME_MATCHER</code>
       <code>static::DEFAULT_DOCUMENT_TYPE</code>
       <code>static::CONTENT_TYPE_META_TAG</code>
       <code>static::CONTENT_TYPE_META_TAG</code>
       <code>static::CONTENT_TYPE_META_TAG</code>
+      <code>static::TAGNAME_ALLOWED_BEFORE_BODY_MATCHER</code>
```
[the remark this answers is not in the document]
Comment (JakeQZ) [reply psalm.baseline.xml]: Resolved in rebase.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 5]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+        $contentTypeMetaTagMatchCount = \preg_match(
+            '%<meta(?=\\s)[^>]*\\shttp-equiv=(["\']?+)Content-Type\\g{-1}[\\s/>]%i',
+            $html,
+            $matches,
+            PREG_OFFSET_CAPTURE
+        );
+        if (\is_int($contentTypeMetaTagMatchCount) && $contentTypeMetaTagMatchCount > 0) {
+            /** @psalm-var array<int, array{0:string, 1:int}> $matches */
+            $matchPosition = $matches[0][1];
+            $htmlBefore = \substr($html, 0, $matchPosition);
```
[the remark this answers is not in the document]
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: Good idea - now the HTML before is captured.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 6]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+    {
+        $contentTypeMetaTagMatchCount = \preg_match(
+            '%<meta(?=\\s)[^>]*\\shttp-equiv=(["\']?+)Content-Type\\g{-1}[\\s/>]%i',
+            $html,
+            $matches,
+            PREG_OFFSET_CAPTURE
+        );
+        if (\is_int($contentTypeMetaTagMatchCount) && $contentTypeMetaTagMatchCount > 0) {
+            /** @psalm-var array<int, array{0:string, 1:int}> $matches */
+            $matchPosition = $matches[0][1];
```
[the remark this answers is not in the document]
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: Now doing something similar in the reworked code.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 7]
```diff
@@ -302,6 +308,111 @@ private function addContentTypeMetaTag(string $html): string
...
+    private function hasContentTypeMetaTagInHead(string $html): bool
+    {
+        $contentTypeMetaTagMatchCount = \preg_match(
+            '%<meta(?=\\s)[^>]*\\shttp-equiv=(["\']?+)Content-Type\\g{-1}[\\s/>]%i',
+            $html,
+            $matches,
+            PREG_OFFSET_CAPTURE
+        );
+        if (\is_int($contentTypeMetaTagMatchCount) && $contentTypeMetaTagMatchCount > 0) {
+            /** @psalm-var array<int, array{0:string, 1:int}> $matches */
```
[the remark this answers is not in the document]
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: No longer required in the reworked code, testing `isset($matches[0])`.

File: src/HtmlProcessor/AbstractHtmlProcessor.php (hunk 1 above)
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: Shortened.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 8]
```diff
@@ -385,7 +390,7 @@ private function hasEndOfHeadElement(string $html): bool
      */
     private function removeHtmlComments(string $html): string
     {
-        $result = \preg_replace('/<!--[^-]*+(?:-(?!->)[^-]*+)*+(?:-->|$)/', '', $html);
+        $result = \preg_replace(static::HTML_COMMENT_PATTERN, '', $html);
```
Comment (oliverklee) [inline src/HtmlProcessor/AbstractHtmlProcessor.php:393]: Please generally let's use `self::`, not `static:: `, in order to commicate that this constant is not intended to be overwritten in subclasses.

File: src/HtmlProcessor/AbstractHtmlProcessor.php [hunk 9]
```diff
@@ -405,7 +410,7 @@ private function removeHtmlComments(string $html): string
      */
     private function removeHtmlTemplateElements(string $html): string
     {
-        $result = \preg_replace('%<template[\\s>][^<]*+(?:<(?!/template>)[^<]*+)*+(?:</template>|$)%i', '', $html);
+        $result = \preg_replace(static::HTML_TEMPLATE_ELEMENT_PATTERN, '', $html);
```
Comment (oliverklee) [inline src/HtmlProcessor/AbstractHtmlProcessor.php:413]: Ditto.

File: src/HtmlProcessor/AbstractHtmlProcessor.php (hunk 2 above)
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: Changed "including any unclosed" to "including any which are unterminated".

**Review by oliverklee — CHANGES_REQUESTED** [review]

File: src/HtmlProcessor/AbstractHtmlProcessor.php (hunk 3 above)
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: Moved to a constant, and similaraly for the pattern used by `removeHtmlTemplateElements`.

File: src/HtmlProcessor/AbstractHtmlProcessor.php (hunk 8 above)
Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php:394]: This would also fix the Psalm errors.  However, I'd draw your attention to #487 for #228 in which the code was changed throughout to use `static::` rather than `self::` for accessing all constants.

Comment (oliverklee) [reply src/HtmlProcessor/AbstractHtmlProcessor.php:394]: Ah, I see. This was before I had understood when to use `self::` and when to use `static::` (both concerning the functional difference as well as what this communicates). :-)

Comment (JakeQZ) [reply src/HtmlProcessor/AbstractHtmlProcessor.php]: OK.  I think `self::` is correct to access class constants - they are, after all, constants (so really not expected to be overridden).

**Review by oliverklee — APPROVED** [review]
